"""Conformance tests for machine-readable criterion schema.

Three test classes:

1. SchemaConformance — every YAML in data/policy/criteria/ deserializes into
   CriterionSpec without error. Catches typos, missing fields, unknown operators.

2. SourceDocConformance — for each criterion, the policy_ref.file exists and
   the text_fragment appears verbatim in it. If the policy document is edited
   and the fragment shifts, this test fails and forces an explicit update to
   the criterion encoding.

3. PredicateEvaluation — runs hand-authored (bundle_fragments → expected)
   cases from tests/policy/fixtures/. Expected outcomes were confirmed by the
   policy author, not generated by an LLM (same rule as the Chapter B golden
   set). A failing test here means the predicate evaluates differently from
   the confirmed ground truth.
"""
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from prior_auth_agent.policy.evaluator import evaluate_criterion
from prior_auth_agent.policy.registry import load_all
from prior_auth_agent.policy.schema import CriterionSpec

CRITERIA_DIR = REPO_ROOT / "data" / "policy" / "criteria"
POLICIES_DIR = REPO_ROOT / "data" / "policies"
FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ── Schema conformance ─────────────────────────────────────────────────────────


class TestSchemaConformance:
    def test_criteria_directory_has_files(self):
        assert list(CRITERIA_DIR.glob("*.yaml")), "No criterion YAML files found"

    @pytest.mark.parametrize("yaml_path", sorted(CRITERIA_DIR.glob("*.yaml")))
    def test_deserializes_without_error(self, yaml_path: Path):
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        spec = CriterionSpec.model_validate(data)
        assert spec.criterion_id
        assert spec.version
        assert spec.predicate is not None

    @pytest.mark.parametrize("yaml_path", sorted(CRITERIA_DIR.glob("*.yaml")))
    def test_required_text_fields_non_empty(self, yaml_path: Path):
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        spec = CriterionSpec.model_validate(data)
        assert spec.criterion_text.strip(), f"{yaml_path.name}: criterion_text blank"
        assert spec.policy_ref.file, f"{yaml_path.name}: policy_ref.file blank"
        assert spec.policy_ref.text_fragment, f"{yaml_path.name}: text_fragment blank"
        assert spec.policy_ref.section, f"{yaml_path.name}: section blank"

    def test_load_all_returns_all_criteria(self):
        yaml_count = len(list(CRITERIA_DIR.glob("*.yaml")))
        specs = load_all(CRITERIA_DIR)
        assert len(specs) == yaml_count


# ── Source document conformance ────────────────────────────────────────────────


class TestSourceDocConformance:
    @pytest.mark.parametrize("yaml_path", sorted(CRITERIA_DIR.glob("*.yaml")))
    def test_policy_ref_file_exists(self, yaml_path: Path):
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        spec = CriterionSpec.model_validate(data)
        policy_file = POLICIES_DIR / spec.policy_ref.file
        assert policy_file.exists(), (
            f"{spec.criterion_id}: policy_ref.file '{spec.policy_ref.file}' not found "
            f"in {POLICIES_DIR}"
        )

    @pytest.mark.parametrize("yaml_path", sorted(CRITERIA_DIR.glob("*.yaml")))
    def test_text_fragment_verbatim_in_source(self, yaml_path: Path):
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        spec = CriterionSpec.model_validate(data)
        policy_file = POLICIES_DIR / spec.policy_ref.file
        if not policy_file.exists():
            pytest.skip(f"Policy file missing: {spec.policy_ref.file}")
        policy_text = policy_file.read_text(encoding="utf-8")
        assert spec.policy_ref.text_fragment in policy_text, (
            f"{spec.criterion_id}: text_fragment not found verbatim in "
            f"'{spec.policy_ref.file}'.\n"
            f"Fragment: {spec.policy_ref.text_fragment!r}"
        )


# ── Predicate evaluation conformance ──────────────────────────────────────────


def _collect_cases() -> list[pytest.param]:
    specs = {s.criterion_id: s for s in load_all(CRITERIA_DIR)}
    params = []
    for fixture_path in sorted(FIXTURES_DIR.glob("*_cases.yaml")):
        fixture = yaml.safe_load(fixture_path.read_text(encoding="utf-8"))
        cid = fixture["criterion_id"]
        spec = specs.get(cid)
        if spec is None:
            continue
        for case in fixture.get("cases", []):
            params.append(pytest.param(
                spec,
                case,
                id=f"{cid}::{case['id']}",
            ))
    return params


class TestPredicateEvaluation:
    @pytest.mark.parametrize("spec,case", _collect_cases())
    def test_evaluates_to_expected(self, spec: CriterionSpec, case: dict):
        bundle_fragments = case.get("bundle_fragments") or {}
        result = evaluate_criterion(spec, bundle_fragments)
        assert result.status == case["expected"], (
            f"\n{spec.criterion_id}::{case['id']}\n"
            f"Description: {case['description']}\n"
            f"Expected:    {case['expected']!r}\n"
            f"Got:         {result.status!r}\n"
            f"Reason:      {result.reason}"
        )
